/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include <alpr.h>
#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
/* Header for class com_example_testapp_NativeAlpr */

#define CONFIG_FILE	"/etc/openalpr.conf"

#ifndef _Included_com_example_testapp_NativeAlpr
#define _Included_com_example_testapp_NativeAlpr


#ifdef __cplusplus
extern "C" {
#endif


jstring _recognize(JNIEnv *, jobject,
                   jstring , jstring , jstring ,
                   jstring , jint );

std::string detectandshow( alpr::Alpr* , cv::Mat , std::string );

std::string errorJsonString(std::string);

/*
 * Class:     com_example_testapp_NativeAlpr
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_akshika_opencvtest_NativeAlpr_stringFromJNI
  (JNIEnv *, jobject);


/*
 * Class:     org_openalpr_AlprJNIWrapper
 * Method:    recognize
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_akshika_opencvtest_NativeAlpr_recognize
        (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_openalpr_AlprJNIWrapper
 * Method:    recognizeWithCountryNRegion
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_akshika_opencvtest_NativeAlpr_recognizeWithCountryNRegion
        (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     org_openalpr_AlprJNIWrapper
 * Method:    recognizeWithCountryRegionNConfig
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_akshika_opencvtest_NativeAlpr_recognizeWithCountryRegionNConfig
        (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint);


#ifdef __cplusplus
}
#endif
#endif
